### ISSUE TITLE
Files in mpg format cannot be opened

### ISSUE THREAD

**Issue by qinjianzhanqing** [Kuba-MV/MVLib-DotNet#2]
Files in mpg format cannot be opened。

**Comment by Kuba-MV** [comment]
Mpg is pretty legacy format, however MVLib should play it without sweat. 

You didn't attached log, but i can assume you are using MV_Auto decoding type. 

It means MVLib will attempt to use DX11VA accelerated decoding . In this case there is high probability that your GPU is not able to decode Mpg using Dx11 or DXVA. You should use software decoding. 

MVLib supports software decoding via YUV or RGB. I strongly recommend to use YUV decoding because is fastest way to decode video in cpu.

 
Before opening mpg video set decoding format to MV_DecodingTypeEnum.MV_YUV420P

Or even better you can write short code to support automatic fallback into sw decoding if hw decoding will fail.

In your class members define

`private string currentFileName = string.Empty;`

In constructor of your class register MediaStateChanged event

`mvPlayer1.MediaStateChanged += MvPlayer1_MediaStateChanged;`

and use MediaStateChanged like this:

`

            if (mvPlayer1.MediaState == MV_PlayerStateEnum.Error && mvPlayer1.DecodingType == MV_DecodingTypeEnum.MV_Auto)
            {
                //close failed source
                mvPlayer1.Close();

                //change decoding type into sw yuv decoding
                mvPlayer1.DecodingType = MV_DecodingTypeEnum.MV_YUV420P;
                
                mvPlayer1.OpenMediaAsync(currentFileName);
            }

`

I added fallback support to both WinForms and WPF samples, so you can open them and check how it works,

[WinForms sample](https://github.com/Kuba-MV/MVLib-DotNet/releases/download/v1.0.0.1s_WinForms/MVLib.DotNet.WinForms.Sample.1.0.0.1.zip)

[WPF sample](https://github.com/Kuba-MV/MVLib-DotNet/releases/download/v1.0.0.1s_WPF/MVLib.DotNet.WPF.Sample.1.0.0.1.zip)

Let me know if it solved your issue

**Comment by qinjianzhanqing** [comment]
Solved thank you,Hope to improve automatic recognition decoding。
